// <auto-generated />
using System;
using HR.Modules.Companies.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Modules.Companies.Migrations
{
    [DbContext(typeof(CompaniesDbContext))]
    [Migration("20260826031813_AddRecruitmentSettingsToCompanySettings")]
    partial class AddRecruitmentSettingsToCompanySettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("companies")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR.Modules.Companies.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("companies", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CompanyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line2");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Type")
                        .IsUnique();

                    b.ToTable("company_addresses", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CompanyBranding", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailLogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("email_logo_url");

                    b.Property<string>("PrimaryLogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("primary_logo_url");

                    b.Property<string>("SmallLogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("small_logo_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CompanyId");

                    b.ToTable("company_branding", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CompanySettings", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("AcknowledgementReminderIntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("acknowledgement_reminder_interval_days");

                    b.Property<int>("AssetNumberMinimumLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("asset_number_minimum_length");

                    b.Property<string>("AssetNumberMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("asset_number_mode");

                    b.Property<string>("AssetNumberPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset_number_prefix");

                    b.Property<bool>("AutoDisableAccessOnLeavingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_disable_access_on_leaving_date");

                    b.Property<int>("CandidateRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(730)
                        .HasColumnName("candidate_retention_days");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultAcknowledgementStatement")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("I confirm that I have read and understood this document.")
                        .HasColumnName("default_acknowledgement_statement");

                    b.Property<decimal>("DefaultHolidayAllowance")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("default_holiday_allowance");

                    b.Property<bool>("DisplaySalaryOnEmployeeProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("display_salary_on_employee_profile");

                    b.Property<int>("EmployeeNumberMinimumLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("employee_number_minimum_length");

                    b.Property<string>("EmployeeNumberMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("employee_number_mode");

                    b.Property<string>("EmployeeNumberPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employee_number_prefix");

                    b.Property<bool>("ExcludePublicHolidaysFromLeave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("exclude_public_holidays_from_leave");

                    b.Property<bool>("ExcludePublicHolidaysFromSickness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exclude_public_holidays_from_sickness");

                    b.Property<int>("FitNoteRequiredAfterDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7)
                        .HasColumnName("fit_note_required_after_days");

                    b.Property<int>("FrequentAbsenceCountThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("frequent_absence_count_threshold");

                    b.Property<int>("FrequentAbsenceWindowDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(365)
                        .HasColumnName("frequent_absence_window_days");

                    b.Property<decimal>("HoursPerDay")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("hours_per_day");

                    b.Property<int>("LeaveYearStartMonth")
                        .HasColumnType("integer")
                        .HasColumnName("leave_year_start_month");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("locale");

                    b.Property<int>("LongAbsenceDayThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(28)
                        .HasColumnName("long_absence_day_threshold");

                    b.Property<string>("MobileRegex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("^(?:\\+44\\s?|0)7\\d{3}(?:\\s?\\d{3}){2}$")
                        .HasColumnName("mobile_regex");

                    b.Property<int>("NextAssetNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("next_asset_number");

                    b.Property<int>("NextEmployeeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("next_employee_number");

                    b.Property<int>("NoticePeriodLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("notice_period_length");

                    b.Property<string>("NoticePeriodUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Months")
                        .HasColumnName("notice_period_unit");

                    b.Property<bool>("OfferApprovalRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("offer_approval_required");

                    b.Property<string>("PostcodeRegex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("^[A-Za-z]{1,2}\\d[A-Za-z\\d]?\\s?\\d[A-Za-z]{2}$")
                        .HasColumnName("postcode_regex");

                    b.Property<int?>("ProbationCheckpointDay1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("probation_checkpoint_day_1");

                    b.Property<int?>("ProbationCheckpointDay2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("probation_checkpoint_day_2");

                    b.Property<int?>("ProbationCheckpointDay3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("probation_checkpoint_day_3");

                    b.Property<int>("ProbationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("probation_months");

                    b.Property<int>("ReturnToWorkRequiredAfterDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("return_to_work_required_after_days");

                    b.Property<string>("TelephoneRegex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("^(?:\\+44\\s?|0)(?:\\d\\s?){9,10}$")
                        .HasColumnName("telephone_regex");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VacancyApprovalRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("vacancy_approval_required");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<int>("WeekdayPatternOccurrenceThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("weekday_pattern_occurrence_threshold");

                    b.Property<int>("WeekdayPatternWindowDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(365)
                        .HasColumnName("weekday_pattern_window_days");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer")
                        .HasColumnName("working_days");

                    b.HasKey("CompanyId");

                    b.ToTable("company_settings", "companies", t =>
                        {
                            t.HasCheckConstraint("CK_company_settings_asset_number_minimum_length", "asset_number_minimum_length BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_company_settings_candidate_retention_days", "candidate_retention_days BETWEEN 90 AND 3650");

                            t.HasCheckConstraint("CK_company_settings_default_holiday_allowance", "default_holiday_allowance >= 0");

                            t.HasCheckConstraint("CK_company_settings_employee_number_minimum_length", "employee_number_minimum_length BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_company_settings_leave_year_start_month", "leave_year_start_month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_company_settings_next_asset_number", "next_asset_number > 0");

                            t.HasCheckConstraint("CK_company_settings_next_employee_number", "next_employee_number > 0");

                            t.HasCheckConstraint("CK_company_settings_probation_months", "probation_months > 0");

                            t.HasCheckConstraint("CK_company_settings_working_days", "working_days BETWEEN 1 AND 127");
                        });
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CustomerBillingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveEmployees")
                        .HasColumnType("integer")
                        .HasColumnName("active_employees");

                    b.Property<int>("ChargeableEmployees")
                        .HasColumnType("integer")
                        .HasColumnName("chargeable_employees");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<decimal>("Discounts")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discounts");

                    b.Property<int>("FutureStarters")
                        .HasColumnType("integer")
                        .HasColumnName("future_starters");

                    b.Property<int>("Leavers")
                        .HasColumnType("integer")
                        .HasColumnName("leavers");

                    b.Property<decimal>("MonthlyTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monthly_total");

                    b.Property<decimal>("PricePerEmployee")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_employee");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_customer_billing_snapshots_company_id");

                    b.HasIndex("CompanyId", "ComputedAt")
                        .HasDatabaseName("ix_customer_billing_snapshots_company_id_computed_at");

                    b.ToTable("customer_billing_snapshots", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CustomerSubscription", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("AdminForcedReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("admin_forced_read_only");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset?>("DeletionCancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_cancelled_at");

                    b.Property<DateTimeOffset?>("DeletionExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_executed_at");

                    b.Property<DateTimeOffset?>("DeletionScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_scheduled_at");

                    b.Property<Guid?>("DeletionScheduledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deletion_scheduled_by");

                    b.Property<string>("PriceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("price_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTimeOffset>("TrialExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_expires_at");

                    b.Property<DateTimeOffset>("TrialStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_started_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CompanyId");

                    b.ToTable("customer_subscriptions", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("outbox_messages", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.PlatformMetricsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveCompanies")
                        .HasColumnType("integer")
                        .HasColumnName("active_companies");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("integer")
                        .HasColumnName("active_users");

                    b.Property<int>("BackgroundJobsSucceededTotal")
                        .HasColumnType("integer")
                        .HasColumnName("background_jobs_succeeded_total");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<long>("StorageConsumedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_consumed_bytes");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_metrics_snapshots_snapshot_date");

                    b.ToTable("platform_metrics_snapshots", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.PlatformSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DefaultMonthlyPriceGbp")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("default_monthly_price_gbp");

                    b.Property<string>("FeatureFlagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("feature_flags_json");

                    b.Property<bool>("MaintenanceModeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("maintenance_mode_enabled");

                    b.Property<string>("MaintenanceModeMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("maintenance_mode_message");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasDefaultValue("support@hrplatform.com")
                        .HasColumnName("support_email");

                    b.Property<int>("TrialLengthDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(14)
                        .HasColumnName("trial_length_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("platform_settings", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Date")
                        .HasDatabaseName("IX_public_holidays_company_id_date");

                    b.ToTable("public_holidays", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.SupportSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IssuedByAdminEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("issued_by_admin_email");

                    b.Property<Guid>("IssuedByAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_admin_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_support_sessions_company_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_support_sessions_token_hash");

                    b.ToTable("support_sessions", "companies");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CompanyAddress", b =>
                {
                    b.HasOne("HR.Modules.Companies.Domain.Company", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CompanyBranding", b =>
                {
                    b.HasOne("HR.Modules.Companies.Domain.Company", null)
                        .WithOne("Branding")
                        .HasForeignKey("HR.Modules.Companies.Domain.CompanyBranding", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CompanySettings", b =>
                {
                    b.HasOne("HR.Modules.Companies.Domain.Company", null)
                        .WithOne("Settings")
                        .HasForeignKey("HR.Modules.Companies.Domain.CompanySettings", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CustomerSubscription", b =>
                {
                    b.HasOne("HR.Modules.Companies.Domain.Company", null)
                        .WithOne()
                        .HasForeignKey("HR.Modules.Companies.Domain.CustomerSubscription", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.Company", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Branding");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
