// <auto-generated />
using System;
using HR.Modules.Companies.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Modules.Companies.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260928000000_CreatePlatformSchema")]
    partial class CreatePlatformSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR.Modules.Companies.Domain.CustomerDatabaseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_key");

                    b.Property<long?>("SchemaOid")
                        .HasColumnType("bigint")
                        .HasColumnName("schema_oid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_customer_database_assignments_company_id");

                    b.HasIndex("DatabaseKey")
                        .HasDatabaseName("ix_customer_database_assignments_database_key");

                    b.HasIndex("Status", "CompanyId")
                        .HasDatabaseName("ix_customer_database_assignments_status_company_id");

                    b.ToTable("customer_database_assignments", "platform");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.PlatformMetricsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveCompanies")
                        .HasColumnType("integer")
                        .HasColumnName("active_companies");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("integer")
                        .HasColumnName("active_users");

                    b.Property<int>("BackgroundJobsSucceededTotal")
                        .HasColumnType("integer")
                        .HasColumnName("background_jobs_succeeded_total");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<long>("StorageConsumedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_consumed_bytes");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_metrics_snapshots_snapshot_date");

                    b.ToTable("platform_metrics_snapshots", "platform");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.PlatformSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DefaultMonthlyPriceGbp")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("default_monthly_price_gbp");

                    b.Property<string>("FeatureFlagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("feature_flags_json");

                    b.Property<bool>("MaintenanceModeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("maintenance_mode_enabled");

                    b.Property<string>("MaintenanceModeMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("maintenance_mode_message");

                    b.Property<decimal>("MinimumMonthlyChargeGbp")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("minimum_monthly_charge_gbp");

                    b.Property<string>("PricingBandsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("pricing_bands_json");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasDefaultValue("support@hrplatform.com")
                        .HasColumnName("support_email");

                    b.Property<int>("TrialLengthDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(14)
                        .HasColumnName("trial_length_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("platform_settings", "platform");
                });

            modelBuilder.Entity("HR.Modules.Companies.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body_json");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.HasKey("OperationId", "CompanyId", "ActorId", "Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "platform");
                });
#pragma warning restore 612, 618
        }
    }
}
