// <auto-generated />
using System;
using HR.Modules.Companies.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Modules.Companies.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260928000000_CreatePlatformContext")]
    partial class CreatePlatformContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR.Modules.Companies.Domain.CustomerDatabaseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_key");

                    b.Property<uint?>("SchemaOid")
                        .HasColumnType("bigint")
                        .HasColumnName("schema_oid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_customer_database_assignments_company_id");

                    b.HasIndex("DatabaseKey")
                        .HasDatabaseName("ix_customer_database_assignments_database_key");

                    b.HasIndex("Status", "CompanyId")
                        .HasDatabaseName("ix_customer_database_assignments_status_company_id");

                    b.ToTable("customer_database_assignments", "platform");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.PlatformMetricsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveCompanies")
                        .HasColumnType("integer")
                        .HasColumnName("active_companies");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("integer")
                        .HasColumnName("active_users");

                    b.Property<int>("BackgroundJobsSucceededTotal")
                        .HasColumnType("integer")
                        .HasColumnName("background_jobs_succeeded_total");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<long>("StorageConsumedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_consumed_bytes");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_metrics_snapshots_snapshot_date");

                    b.ToTable("platform_metrics_snapshots", "platform");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.PlatformSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DefaultMonthlyPriceGbp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("default_monthly_price_gbp")
                        .HasDefaultValue(0m);

                    b.Property<string>("FeatureFlagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_flags_json")
                        .HasDefaultValue("{}");

                    b.Property<bool>("MaintenanceModeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("maintenance_mode_enabled")
                        .HasDefaultValue(false);

                    b.Property<string>("MaintenanceModeMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("maintenance_mode_message");

                    b.Property<decimal>("MinimumMonthlyChargeGbp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("minimum_monthly_charge_gbp")
                        .HasDefaultValue(0m);

                    b.Property<string>("PricingBandsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pricing_bands_json")
                        .HasDefaultValue("[]");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("support_email")
                        .HasDefaultValue("support@hrplatform.com");

                    b.Property<int>("TrialLengthDays")
                        .HasColumnType("integer")
                        .HasColumnName("trial_length_days")
                        .HasDefaultValue(14);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("platform_settings", "platform");
                });

            modelBuilder.Entity("HR.SharedKernel.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("Scope", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_scope_idempotency_key");

                    b.ToTable("idempotency_records", "platform");
                });

            modelBuilder.Entity("HR.Modules.Companies.Domain.CustomerDatabaseAssignment", b =>
                {
                    b.HasOne("HR.Modules.Companies.Domain.Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_customer_database_assignments_companies_company_id");
                });

#pragma warning restore 612, 618
        }
    }
}
