<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\HR.SharedKernel\HR.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Modules\HR.Modules.Tasks.Contracts\HR.Modules.Tasks.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\HR.Modules.Employees.Contracts\HR.Modules.Employees.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
