namespace HR.Infrastructure.Abstractions;

public enum NotificationType
{
    TaskAssigned     = 1,
    TaskDueSoon      = 2,
    TaskOverdue      = 3,
    LeaveApproved    = 4,
    LeaveRejected    = 5,
    LeaveRequested   = 6,
    DocumentExpiring = 7,
    DocumentExpired  = 8,
    TaskCompleted         = 9,
    AssetAssigned         = 10,
    AssetReturnRequested  = 11,
    AssetAcknowledgementReminder = 12,
    AssetReturnReminder          = 13,
    AssetAcknowledgementOverdue  = 14,
    AssetReturnOverdue           = 15,
    SicknessRecorded             = 16,
    SicknessEvidenceReminder     = 17,
    SicknessEvidenceOverdue      = 18,
    ReturnToWorkReviewReminder   = 19,
    ReturnToWorkReviewOverdue    = 20,
    InterviewScheduled           = 21,
    InterviewFeedbackOverdue     = 22,
    InterviewReminder            = 23,
    OnboardingStarted            = 24,
    OnboardingTaskOverdue        = 25,
    OffboardingStarted           = 26,
    OffboardingTaskOverdue       = 27,
    OffboardingCompleted         = 28,
    ProfilePhotoApproved         = 29,
    ProfilePhotoRejected         = 30,
    SharedCompanyDocumentAcknowledgementReminder = 31,
    SharedCompanyDocumentAcknowledgementOverdue  = 32,
}
