using HR.Infrastructure.Abstractions;

namespace HR.Modules.Reporting.Features.ExportCompanyDocumentAcknowledgementReport;

internal sealed record ExportCompanyDocumentAcknowledgementReportResponse(ReportExportFile File);
