<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\HR.SharedKernel\HR.SharedKernel.csproj" />
    <ProjectReference Include="..\HR.Modules.Employees.Contracts\HR.Modules.Employees.Contracts.csproj" />
    <ProjectReference Include="..\HR.Modules.Companies.Contracts\HR.Modules.Companies.Contracts.csproj" />
    <ProjectReference Include="..\..\Infrastructure\HR.Infrastructure.Abstractions\HR.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HR.Architecture.Tests" />
    <InternalsVisibleTo Include="HR.Modules.Reporting.Tests" />
    <InternalsVisibleTo Include="HR.Integration.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
