// <auto-generated />
using System;
using HR.Modules.Documents.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Modules.Documents.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20260618120000_AddEmployeeDocument")]
    partial class AddEmployeeDocument
    {
    }
}
