using HR.SharedKernel;

namespace HR.Modules.Companies.Features.GenerateSupportSession;

/// <summary>
/// Records a platform-administrator support session grant (Support epic). Plugs into the existing
/// cross-cutting IAuditEventPublisher/AuditDbContext infrastructure, same as
/// HR.Modules.Companies.Features.ExtendCustomerTrial.Audit. Deliberately excludes any token
/// material (raw or hashed) from the audit payload — the token is single-use, 256-bit-entropy
/// credential material and must never be logged/audited.
/// </summary>
internal sealed record SupportSessionGeneratedAuditEvent(
    Guid CompanyId,
    Guid SupportSessionId,
    Guid? ActorUserId,
    DateTimeOffset OccurredAt,
    string Reason) : IAuditEvent
{
    string IAuditEvent.EventType => "support.session-generated";
    string IAuditEvent.EntityType => "SupportSession";
    Guid IAuditEvent.EntityId => SupportSessionId;
    Guid? IAuditEvent.ActorEmployeeId => null;
    Guid? IAuditEvent.CorrelationId => null;
    string? IAuditEvent.Summary => $"Support session generated by platform administrator. Reason: {Reason}";
    object? IAuditEvent.Before => null;
    object? IAuditEvent.After => null;
    object? IAuditEvent.Metadata => new { Reason };
}
