using HR.Modules.Tasks.Contracts;
using HR.Modules.Probation.Domain;
using HR.Modules.Probation.Persistence;
using HR.Modules.Employees.Contracts;
using HR.SharedKernel;
using HR.SharedKernel.Idempotency;
using HR.Infrastructure.Abstractions;
using Microsoft.EntityFrameworkCore;

namespace HR.Modules.Probation.Services;

/// <summary>
/// Applies the follow-up workflow that must happen every time a probation is extended
/// (PROB-01): supersede any other still-pending FinalDecision review/task for the record,
/// create a one-off ExtensionConfirmation review + task, schedule a fresh FinalDecision
/// review + task for the new expected end date, and notify the manager, HR administrators
/// and the employee.
///
/// Ticket 15 (P1): previously this method's own idempotency was entirely borrowed from its
/// caller's "review was not already completed" guard — safe for a single in-flight request, but
/// NOT safe for a Tasks-dispatch replay: if the primary review/record mutation committed and the
/// process was interrupted before (or during) this method, a replayed dispatch would see the
/// review already Completed and never call back in here at all, permanently losing the extension
/// review/task/audit/integration-event follow-up. When <paramref name="dispatchOperationId"/> is
/// supplied (the Tasks-dispatch path), the two new review rows are created under this module's own
/// idempotency record keyed to that operation, so a recovered call (see
/// CompleteProbationReviewFromTaskAction.RecoverExtensionEffectsAsync) replays the SAME review ids
/// instead of creating a duplicate pair, and every downstream effect keyed off those ids
/// (task-creation idempotency keys, the audit event's deterministic EventId) is then itself a safe
/// no-op to repeat. The direct API path (CompleteProbationReviewHandler) has no dispatch identity
/// and passes null — for that path, only-once-per-request is still sufficient, unchanged from
/// before.
/// </summary>
internal sealed class ProbationExtensionService(
    ProbationDbContext dbContext,
    ITaskCreator taskCreator,
    ITaskCanceller taskCanceller,
    IEmployeeNameReader employeeNameReader,
    IHrAdministratorDirectory hrAdministratorDirectory,
    INotificationWriter notificationWriter,
    IAuditEventPublisher auditPublisher,
    IIntegrationEventPublisher integrationEventPublisher)
{
    private sealed record ExtensionReviewPair(Guid ExtensionConfirmationReviewId, Guid NewFinalReviewId);

    public async Task ApplyAsync(
        ProbationRecord record,
        ProbationReview sourceReview,
        DateOnly previousExpectedEndDate,
        DateOnly newExpectedEndDate,
        string extensionReason,
        Guid decisionMakerEmployeeId,
        DateOnly decisionDate,
        DateTimeOffset now,
        CancellationToken cancellationToken,
        Guid? dispatchOperationId = null)
    {
        // Supersede any other still-pending FinalDecision reviews for this record (e.g. one
        // already generated by the daily scheduling job for the pre-extension expected end
        // date) — they no longer apply once the expected end date moves. The review that was
        // just completed (sourceReview) is excluded; its own status transition to Completed is
        // handled by the caller.
        var obsoleteFinalReviews = await dbContext.ProbationReviews
            .Where(r => r.CompanyId == record.CompanyId
                && r.ProbationRecordId == record.Id
                && r.ReviewType == ProbationReviewType.FinalDecision
                && r.Status == ProbationReviewStatus.Pending
                && r.Id != sourceReview.Id)
            .ToListAsync(cancellationToken);

        // Also close any task still open against the review that was just completed — the
        // ITaskCompleter-driven path (CompleteProbationReviewFromTaskAction) already closes its
        // own originating task, but the direct API path (CompleteProbationReviewHandler) does
        // not, so a task pointing at sourceReview.Id could otherwise be left open indefinitely.
        // Safe no-op if no matching open task exists.
        await taskCanceller.CancelBySourceEntityAsync(
            record.CompanyId, sourceReview.Id, TaskSource.Probation, TaskActionType.Review, cancellationToken);

        foreach (var obsolete in obsoleteFinalReviews)
        {
            obsolete.Cancel(sourceReview.Id, now);
            await taskCanceller.CancelBySourceEntityAsync(
                record.CompanyId, obsolete.Id, TaskSource.Probation, TaskActionType.Review, cancellationToken);
        }

        var extensionConfirmationReview = ProbationReview.Create(
            Guid.NewGuid(), record.CompanyId, record.Id, ProbationReviewType.ExtensionConfirmation, decisionDate, now);

        var newFinalReview = ProbationReview.Create(
            Guid.NewGuid(), record.CompanyId, record.Id, ProbationReviewType.FinalDecision, newExpectedEndDate, now);

        dbContext.ProbationReviews.Add(extensionConfirmationReview);
        dbContext.ProbationReviews.Add(newFinalReview);

        if (dispatchOperationId is { } operationId && operationId != Guid.Empty)
        {
            // Ticket 15 (P1): commit the new review pair AND the idempotency record atomically —
            // a replayed call for the SAME dispatch operation gets back the original pair's ids
            // instead of inserting a second pair.
            var scope = new IdempotencyScope("ProbationExtensionApply", record.CompanyId, decisionMakerEmployeeId);
            var idempotencyKey = $"TaskCompletionDispatch:{operationId}";
            var fingerprint = DbContextIdempotencyExtensions.Fingerprint(
                new { sourceReview.Id, newExpectedEndDate });

            var outcome = await dbContext.SaveIdempotentAsync<IdempotencyRecord, ExtensionReviewPair>(
                dbContext.IdempotencyRecords,
                scope,
                idempotencyKey,
                fingerprint,
                statusCode: 200,
                response: new ExtensionReviewPair(extensionConfirmationReview.Id, newFinalReview.Id),
                now,
                cancellationToken);

            if (outcome.Kind == IdempotencyOutcomeKind.Replayed)
            {
                // Another attempt for this exact operation already created the pair — reload the
                // originals rather than proceeding with the (now-detached, unsaved) entities this
                // call tried to add.
                extensionConfirmationReview = await dbContext.ProbationReviews
                    .SingleAsync(r => r.Id == outcome.Response!.ExtensionConfirmationReviewId, cancellationToken);
                newFinalReview = await dbContext.ProbationReviews
                    .SingleAsync(r => r.Id == outcome.Response!.NewFinalReviewId, cancellationToken);
            }
        }
        else
        {
            await dbContext.SaveChangesAsync(cancellationToken);
        }

        var names = await employeeNameReader.GetNamesAsync(record.CompanyId, [record.EmployeeId], cancellationToken);
        var employeeName = names.GetValueOrDefault(record.EmployeeId, "Unknown Employee");

        await taskCreator.CreateAsync(
            record.CompanyId,
            decisionMakerEmployeeId,
            $"Confirm probation extension — {employeeName}",
            $"Probation for {employeeName} was extended to {newExpectedEndDate:d MMM yyyy}. Reason: {extensionReason}",
            TaskPriority.High,
            TaskSource.Probation,
            TaskActionType.Review,
            decisionDate,
            assignedEmployeeId: record.ManagerEmployeeId,
            assignedUserId: record.ManagerEmployeeId,
            sourceEntityId: extensionConfirmationReview.Id,
            cancellationToken,
            notifyAssignee: false,
            // Ticket 15 (P1): stable per-review key — a recovered call reusing the same
            // extensionConfirmationReview.Id (via the idempotency-record replay above) cannot
            // create a second confirmation task.
            idempotencyKey: $"ProbationExtensionConfirmationTask:{extensionConfirmationReview.Id}");

        await taskCreator.CreateAsync(
            record.CompanyId,
            decisionMakerEmployeeId,
            $"Complete probation review — {employeeName}",
            $"Probation final decision due {newExpectedEndDate:d MMM yyyy} (extended).",
            TaskPriority.High,
            TaskSource.Probation,
            TaskActionType.Review,
            newExpectedEndDate,
            assignedEmployeeId: record.ManagerEmployeeId,
            assignedUserId: record.ManagerEmployeeId,
            sourceEntityId: newFinalReview.Id,
            cancellationToken,
            notifyAssignee: false,
            idempotencyKey: $"ProbationExtensionFinalReviewTask:{newFinalReview.Id}");

        await NotifyAsync(record, employeeName, extensionReason, newExpectedEndDate, decisionMakerEmployeeId, now, cancellationToken);

        await auditPublisher.PublishAsync(new ProbationExtendedAuditEvent(
            record.CompanyId,
            record.Id,
            record.EmployeeId,
            decisionMakerEmployeeId,
            previousExpectedEndDate,
            newExpectedEndDate,
            HasExtensionReason: !string.IsNullOrWhiteSpace(extensionReason),
            decisionDate,
            extensionConfirmationReview.Id,
            newFinalReview.Id,
            now), cancellationToken);

        // PROB-07: completes the "add timeline events for extended and failed outcomes"
        // requirement — previously only Pass produced an EmployeeTimelineEntry. Body text carries
        // only the new expected end date, never the free-text extension reason.
        await integrationEventPublisher.PublishAsync(
            new ProbationExtendedIntegrationEvent(record.CompanyId, record.EmployeeId, record.Id, newExpectedEndDate, now),
            cancellationToken);
    }

    private async Task NotifyAsync(
        ProbationRecord record,
        string employeeName,
        string extensionReason,
        DateOnly newExpectedEndDate,
        Guid decisionMakerEmployeeId,
        DateTimeOffset now,
        CancellationToken cancellationToken)
    {
        var title = $"Probation extended — {employeeName}";
        var body = $"Probation has been extended to {newExpectedEndDate:d MMM yyyy}. Reason: {extensionReason}";

        var recipientIds = new HashSet<Guid> { record.EmployeeId };

        if (record.ManagerEmployeeId != decisionMakerEmployeeId)
            recipientIds.Add(record.ManagerEmployeeId);

        var hrAdministratorIds = await hrAdministratorDirectory.GetHrAdministratorEmployeeIdsAsync(
            record.CompanyId, cancellationToken);

        foreach (var hrAdminId in hrAdministratorIds)
            recipientIds.Add(hrAdminId);

        foreach (var recipientId in recipientIds)
        {
            await notificationWriter.WriteAsync(
                Guid.NewGuid(),
                record.CompanyId,
                recipientId,
                title,
                body,
                record.Id,
                NotificationType.ProbationExtended,
                NotificationPriority.High,
                now,
                cancellationToken);
        }
    }
}
