using HR.Modules.Tasks.Contracts;
using HR.Modules.Probation.Domain;
using HR.Modules.Probation.Persistence;
using HR.Modules.Employees.Contracts;
using HR.SharedKernel;
using HR.Infrastructure.Abstractions;
using Microsoft.EntityFrameworkCore;

namespace HR.Modules.Probation.Services;

/// <summary>
/// Applies the follow-up workflow that must happen every time a probation is extended
/// (PROB-01): supersede any other still-pending FinalDecision review/task for the record,
/// create a one-off ExtensionConfirmation review + task, schedule a fresh FinalDecision
/// review + task for the new expected end date, and notify the manager, HR administrators
/// and the employee.
///
/// Callers are responsible for idempotency at the entry point: this method must only be
/// invoked once per extension decision, from inside the "review was not already completed"
/// branch of the review-completion handlers (CompleteProbationReviewHandler and
/// CompleteProbationReviewFromTaskAction both already guard on that before calling in), so a
/// retried/duplicate completion request never reaches this method twice.
/// </summary>
internal sealed class ProbationExtensionService(
    ProbationDbContext dbContext,
    ITaskCreator taskCreator,
    ITaskCanceller taskCanceller,
    IEmployeeNameReader employeeNameReader,
    IHrAdministratorDirectory hrAdministratorDirectory,
    INotificationWriter notificationWriter,
    IAuditEventPublisher auditPublisher,
    IIntegrationEventPublisher integrationEventPublisher)
{
    public async Task ApplyAsync(
        ProbationRecord record,
        ProbationReview sourceReview,
        DateOnly previousExpectedEndDate,
        DateOnly newExpectedEndDate,
        string extensionReason,
        Guid decisionMakerEmployeeId,
        DateOnly decisionDate,
        DateTimeOffset now,
        CancellationToken cancellationToken)
    {
        // Supersede any other still-pending FinalDecision reviews for this record (e.g. one
        // already generated by the daily scheduling job for the pre-extension expected end
        // date) — they no longer apply once the expected end date moves. The review that was
        // just completed (sourceReview) is excluded; its own status transition to Completed is
        // handled by the caller.
        var obsoleteFinalReviews = await dbContext.ProbationReviews
            .Where(r => r.CompanyId == record.CompanyId
                && r.ProbationRecordId == record.Id
                && r.ReviewType == ProbationReviewType.FinalDecision
                && r.Status == ProbationReviewStatus.Pending
                && r.Id != sourceReview.Id)
            .ToListAsync(cancellationToken);

        // Also close any task still open against the review that was just completed — the
        // ITaskCompleter-driven path (CompleteProbationReviewFromTaskAction) already closes its
        // own originating task, but the direct API path (CompleteProbationReviewHandler) does
        // not, so a task pointing at sourceReview.Id could otherwise be left open indefinitely.
        // Safe no-op if no matching open task exists.
        await taskCanceller.CancelBySourceEntityAsync(
            record.CompanyId, sourceReview.Id, TaskSource.Probation, TaskActionType.Review, cancellationToken);

        foreach (var obsolete in obsoleteFinalReviews)
        {
            obsolete.Cancel(sourceReview.Id, now);
            await taskCanceller.CancelBySourceEntityAsync(
                record.CompanyId, obsolete.Id, TaskSource.Probation, TaskActionType.Review, cancellationToken);
        }

        var extensionConfirmationReview = ProbationReview.Create(
            Guid.NewGuid(), record.CompanyId, record.Id, ProbationReviewType.ExtensionConfirmation, decisionDate, now);

        var newFinalReview = ProbationReview.Create(
            Guid.NewGuid(), record.CompanyId, record.Id, ProbationReviewType.FinalDecision, newExpectedEndDate, now);

        dbContext.ProbationReviews.Add(extensionConfirmationReview);
        dbContext.ProbationReviews.Add(newFinalReview);

        await dbContext.SaveChangesAsync(cancellationToken);

        var names = await employeeNameReader.GetNamesAsync(record.CompanyId, [record.EmployeeId], cancellationToken);
        var employeeName = names.GetValueOrDefault(record.EmployeeId, "Unknown Employee");

        await taskCreator.CreateAsync(
            record.CompanyId,
            decisionMakerEmployeeId,
            $"Confirm probation extension — {employeeName}",
            $"Probation for {employeeName} was extended to {newExpectedEndDate:d MMM yyyy}. Reason: {extensionReason}",
            TaskPriority.High,
            TaskSource.Probation,
            TaskActionType.Review,
            decisionDate,
            assignedEmployeeId: record.ManagerEmployeeId,
            assignedUserId: record.ManagerEmployeeId,
            sourceEntityId: extensionConfirmationReview.Id,
            cancellationToken,
            notifyAssignee: false);

        await taskCreator.CreateAsync(
            record.CompanyId,
            decisionMakerEmployeeId,
            $"Complete probation review — {employeeName}",
            $"Probation final decision due {newExpectedEndDate:d MMM yyyy} (extended).",
            TaskPriority.High,
            TaskSource.Probation,
            TaskActionType.Review,
            newExpectedEndDate,
            assignedEmployeeId: record.ManagerEmployeeId,
            assignedUserId: record.ManagerEmployeeId,
            sourceEntityId: newFinalReview.Id,
            cancellationToken,
            notifyAssignee: false);

        await NotifyAsync(record, employeeName, extensionReason, newExpectedEndDate, decisionMakerEmployeeId, now, cancellationToken);

        await auditPublisher.PublishAsync(new ProbationExtendedAuditEvent(
            record.CompanyId,
            record.Id,
            record.EmployeeId,
            decisionMakerEmployeeId,
            previousExpectedEndDate,
            newExpectedEndDate,
            HasExtensionReason: !string.IsNullOrWhiteSpace(extensionReason),
            decisionDate,
            extensionConfirmationReview.Id,
            newFinalReview.Id,
            now), cancellationToken);

        // PROB-07: completes the "add timeline events for extended and failed outcomes"
        // requirement — previously only Pass produced an EmployeeTimelineEntry. Body text carries
        // only the new expected end date, never the free-text extension reason.
        await integrationEventPublisher.PublishAsync(
            new ProbationExtendedIntegrationEvent(record.CompanyId, record.EmployeeId, record.Id, newExpectedEndDate, now),
            cancellationToken);
    }

    private async Task NotifyAsync(
        ProbationRecord record,
        string employeeName,
        string extensionReason,
        DateOnly newExpectedEndDate,
        Guid decisionMakerEmployeeId,
        DateTimeOffset now,
        CancellationToken cancellationToken)
    {
        var title = $"Probation extended — {employeeName}";
        var body = $"Probation has been extended to {newExpectedEndDate:d MMM yyyy}. Reason: {extensionReason}";

        var recipientIds = new HashSet<Guid> { record.EmployeeId };

        if (record.ManagerEmployeeId != decisionMakerEmployeeId)
            recipientIds.Add(record.ManagerEmployeeId);

        var hrAdministratorIds = await hrAdministratorDirectory.GetHrAdministratorEmployeeIdsAsync(
            record.CompanyId, cancellationToken);

        foreach (var hrAdminId in hrAdministratorIds)
            recipientIds.Add(hrAdminId);

        foreach (var recipientId in recipientIds)
        {
            await notificationWriter.WriteAsync(
                Guid.NewGuid(),
                record.CompanyId,
                recipientId,
                title,
                body,
                record.Id,
                NotificationType.ProbationExtended,
                NotificationPriority.High,
                now,
                cancellationToken);
        }
    }
}
