<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HR.ServiceDefaults\HR.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Shared\HR.SharedKernel\HR.SharedKernel.csproj" />
    <ProjectReference Include="..\Infrastructure\HR.Infrastructure\HR.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Companies\HR.Modules.Companies.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.CompanyOnboarding\HR.Modules.CompanyOnboarding.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.DataImport\HR.Modules.DataImport.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Documents\HR.Modules.Documents.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Identity\HR.Modules.Identity.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Employees\HR.Modules.Employees.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Leave\HR.Modules.Leave.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Tasks\HR.Modules.Tasks.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Notifications\HR.Modules.Notifications.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Onboarding\HR.Modules.Onboarding.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Offboarding\HR.Modules.Offboarding.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Probation\HR.Modules.Probation.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Reporting\HR.Modules.Reporting.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Recruitment\HR.Modules.Recruitment.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Assets\HR.Modules.Assets.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Sickness\HR.Modules.Sickness.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b8956337-8148-443a-a35d-733f394a39af</UserSecretsId>
  </PropertyGroup>

</Project>
