<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Content Remove="wwwroot\favicon.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\favicon-dark.png" />
    <None Include="wwwroot\favicon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HR.ServiceDefaults\HR.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Shared\HR.SharedKernel\HR.SharedKernel.csproj" />
    <ProjectReference Include="..\Infrastructure\HR.Infrastructure.Abstractions\HR.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Modules\HR.Modules.Companies.Contracts\HR.Modules.Companies.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="Syncfusion.Blazor.Buttons" />
    <PackageReference Include="Syncfusion.Blazor.Charts" />
    <PackageReference Include="Syncfusion.Blazor.Diagram" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" />
    <PackageReference Include="Syncfusion.Blazor.Grid" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" />
    <PackageReference Include="Syncfusion.Blazor.Kanban" />
    <PackageReference Include="Syncfusion.Blazor.Popups" />
    <PackageReference Include="Syncfusion.Blazor.SplitButtons" />
    <PackageReference Include="Syncfusion.Blazor.Themes" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>17de2f88-b782-4aa9-96f1-f7accb33d2a2</UserSecretsId>
  </PropertyGroup>

</Project>
