// <auto-generated />
using System;
using HR.Modules.Tasks.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Modules.Tasks.Persistence.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    partial class TasksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tasks")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR.Modules.Tasks.Domain.ProgrammaticTaskCompletion", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("AuditPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_published_at");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset?>("CompletionNotificationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_notification_at");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DispatchMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("dispatch")
                        .HasColumnName("dispatch_mode");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("LastResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset_at");

                    b.Property<Guid?>("LastResetBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_reset_by");

                    b.Property<DateTimeOffset?>("NotificationsClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notifications_cleared_at");

                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.Property<int>("ResetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reset_count");

                    b.Property<DateTimeOffset?>("TerminalFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_failure_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("TaskId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_programmatic_task_completions_unconfirmed")
                        .HasFilter("confirmed_at IS NULL");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_programmatic_task_completions_operation_id");

                    b.ToTable("programmatic_task_completions", "tasks");
                });

            modelBuilder.Entity("HR.Modules.Tasks.Domain.TaskCompletionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AdjudicationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("adjudication_count");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<string>("CommandFingerprint")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("command_fingerprint");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_category");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("LastAdjudicatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_adjudicated_at");

                    b.Property<Guid?>("LastAdjudicatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_adjudicated_by");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("LastResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset_at");

                    b.Property<Guid?>("LastResetBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_reset_by");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<bool>("NotificationRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notification_required");

                    b.Property<string>("OutcomeDecision")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("outcome_decision");

                    b.Property<string>("OutcomeReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("outcome_reason");

                    b.Property<string>("PreviousTaskStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_task_status");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ResetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reset_count");

                    b.Property<string>("ResolutionType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resolution_type");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("SnapshotAssignedEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_assigned_employee_id");

                    b.Property<DateTimeOffset?>("SnapshotCapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_captured_at");

                    b.Property<string>("SnapshotTaskDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snapshot_task_description");

                    b.Property<string>("SnapshotTaskTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("snapshot_task_title");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TaskCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("task_completed_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset?>("TerminalFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_failure_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_completion_operations_task_id_active")
                        .HasFilter("status <> 'rejected'");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("task_completion_operations", "tasks");
                });

            modelBuilder.Entity("HR.Modules.Tasks.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_employee_id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_task_items_company_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("task_items", "tasks");
                });

            modelBuilder.Entity("HR.Modules.Tasks.Domain.TaskRecoveryAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("reset")
                        .HasColumnName("action_type");

                    b.Property<int>("AuditAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("audit_attempt_count");

                    b.Property<DateTimeOffset?>("AuditDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_delivered_at");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<bool>("EvidenceSupplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("evidence_supplied");

                    b.Property<DateTimeOffset?>("LastAuditAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_audit_attempt_at");

                    b.Property<string>("LastAuditFailure")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_audit_failure");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation_kind");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ResolutionType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resolution_type");

                    b.Property<string>("ResultingStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resulting_status");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_task_recovery_actions_undelivered")
                        .HasFilter("audit_delivered_at IS NULL");

                    b.HasIndex("CompanyId", "TaskId");

                    b.HasIndex("OperationId", "ActionType", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_task_recovery_actions_operation_sequence");

                    b.ToTable("task_recovery_actions", "tasks");
                });

            modelBuilder.Entity("HR.Modules.Tasks.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body_json");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.HasKey("OperationId", "CompanyId", "ActorId", "Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
