// <auto-generated />
using System;
using HR.Modules.DataImport.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Modules.DataImport.Persistence.Migrations
{
    [DbContext(typeof(DataImportDbContext))]
    [Migration("20260904135357_AddGranularImportConfirmationProgress")]
    partial class AddGranularImportConfirmationProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data_import")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR.Modules.DataImport.Domain.ImportRowError", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ImportSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_session_id");

                    b.Property<string>("RawRowData")
                        .HasColumnType("text")
                        .HasColumnName("raw_row_data");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ImportSessionId");

                    b.ToTable("import_row_errors", "data_import");
                });

            modelBuilder.Entity("HR.Modules.DataImport.Domain.ImportSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_summary");

                    b.Property<int>("FailedRows")
                        .HasColumnType("integer")
                        .HasColumnName("failed_rows");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_key");

                    b.Property<int>("SuccessfulRows")
                        .HasColumnType("integer")
                        .HasColumnName("successful_rows");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Status");

                    b.ToTable("import_sessions", "data_import");
                });

            modelBuilder.Entity("HR.Modules.DataImport.Domain.ImportStagingEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_employee_id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTimeOffset?>("EmployeeCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employee_created_at");

                    b.Property<DateTimeOffset?>("EmployeeCreatedEventPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employee_created_event_published_at");

                    b.Property<DateTimeOffset?>("EmployeeImportedEventPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employee_imported_event_published_at");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employee_number");

                    b.Property<Guid?>("EmploymentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employment_type_id");

                    b.Property<Guid?>("ExistingEmployeeIdToUpdate")
                        .HasColumnType("uuid")
                        .HasColumnName("existing_employee_id_to_update");

                    b.Property<DateTimeOffset?>("FullyConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("ImportSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_session_id");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset?>("ManagerAssignmentProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manager_assignment_processed_at");

                    b.Property<string>("ManagerReference")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("manager_reference");

                    b.Property<DateTimeOffset?>("OpeningLeaveBalanceProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opening_leave_balance_processed_at");

                    b.Property<Guid?>("PositionProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_profile_id");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_data");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("work_email");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ImportSessionId");

                    b.HasIndex("ImportSessionId", "EmployeeNumber");

                    b.HasIndex("ImportSessionId", "WorkEmail");

                    b.ToTable("import_staging_employees", "data_import");
                });

            modelBuilder.Entity("HR.Modules.DataImport.Domain.ImportRowError", b =>
                {
                    b.HasOne("HR.Modules.DataImport.Domain.ImportSession", null)
                        .WithMany()
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Modules.DataImport.Domain.ImportStagingEmployee", b =>
                {
                    b.HasOne("HR.Modules.DataImport.Domain.ImportSession", null)
                        .WithMany()
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
