<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HR.Api\HR.Api.csproj" />
    <ProjectReference Include="..\HR.Web\HR.Web.csproj" />
    <ProjectReference Include="..\HR.Admin.Web\HR.Admin.Web.csproj" />
    <ProjectReference Include="..\HR.Marketing\HR.Marketing.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>399b7d2d-4287-4dc0-8b1c-483251b0b5ab</UserSecretsId>
  </PropertyGroup>

</Project>
